# Generated by Django 5.2 on 2025-05-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='products/')),
                ('product_quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
