# Generated by Django 5.1.7 on 2025-04-09 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Track_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='status',
        ),
    ]
