# Generated by Django 5.1.7 on 2025-04-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Track_app', '0002_remove_orderstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
